default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: weather_app_development

test:
  <<: *default
  database: weather_app_test


production:
  <<: *default
  # database: backend_production
  # username: backend
  # password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
